import pygame
pygame.font.init()

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_SCALAR = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_SCALAR * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 240
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.4

SHOT_RADIUS = 3

SCORE_SCALAR = 30
SCORE_DIMENSIONS = (480, 240)
SCORE_POSITION = (8, 0)
SCORE_FONT = pygame.font.SysFont("helveticaneue", 36)